#python
apigateway-lambda:
    build: ./docker_file
    volumes:
        - ./dev:/home/lambda/dev
    environment:
        - AWS_ACCESS_KEY_ID=xxxxx
        - AWS_SECRET_ACCESS_KEY=xxxxx
        - AWS_DEFAULT_REGION=ap-northeast-1
    ports:
        -  80:80
    command: /bin/bash --login
